### ISSUE TITLE
The code that builds the documentation causes GitHub Action failures with recent dev dependency versions.

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#420]
## Problem/Motivation
Arizona Bootstrap can't follow recommended development dependencies because of a GitHub Action failure.

### Describe the bug
The Hugo static site generator builds the documentation, and a GitHub Action invokes this as part of the linting check that has to pass before we can merge pull requests. Recent versions of the `hugo-bin` dev dependency in package.json cause an error at that point, so currently this is still specifying the 0.78.1 version, while upstream Twitter Bootstrap has already advanced to 0.80.0.

### To Reproduce

Bump the version to 0.80.0, observe a failure in the linting GitHub Action as in
https://github.com/az-digital/arizona-bootstrap/runs/4813153270?check_suite_focus=true
```
Start building sites … 
hugo v0.92.0-B3549403+extended linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
Error: Error building site: POSTCSS: failed to transform "docs/2.0/assets/css/docs.css" (text/css): SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
Total in 617 ms
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/clean-stack/index.js:6:61)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/aggregate-error/index.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERROR: "docs-build" exited with 255.
Error: Process completed with exit code 1.
```
Annoyingly, the Action is using a Docker container, supposedly to guarantee identical behavior to local dev environments, but they cannot reproduce this failure.

## Proposed resolution

The npm package `hugo-bin` wraps the Hugo binary, which in turn invokes some npm packages for additional tasks, such as the PostCSS processing of the generated CSS. Troubleshoot this process.

### Expected behavior

The lint checks themselves should not be the source of any errors.

**Comment by mmunro-ltrr** [comment]
Closed as a side-effect of https://github.com/az-digital/arizona-bootstrap/pull/522
